myapp/caterlist/urls.py
from django.conf.urls import url
import os
from . import views

app_name = 'caterlist'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^chinesetable_list/$', views.CateringList.as_view(), name="chinesetable_list"),
    url(r'^search/$', views.search),
    url(r'^chinesetable/(?P<pk>[0-9]+)/$', views.ChineseDetailView.as_view(), name='chinesetable'),
]

myapp/myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('caterlist.urls')),
    url(r'^admin/', admin.site.urls),
]

myapp/caterlist/models.py
import datetime
import os
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

@python_2_unicode_compatible  # only if you need to support Python 2
class ChineseTable(models.Model):
    # ...
    title_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    image = models.ImageField(upload_to='caterlist/static')
    place_for_service_text = models.CharField(max_length=100)
    location_text = models.CharField(max_length=100)
    description_text = models.TextField()
    price_start_number = models.IntegerField(default=0)
    price_end_number = models.IntegerField(default=1)
    def __str__(self):
        return self.title_text
    def filename(self):
        return os.path.basename(self.image.url)

@python_2_unicode_compatible  # only if you need to support Python 2
class FoodImage(models.Model):
    chinesetable  = models.ForeignKey(ChineseTable, on_delete=models.CASCADE)
    foodImage = models.ImageField(upload_to='caterlist/static')
    foodImage_detail = models.CharField(max_length=10)
    def __str__(self):
        return self.foodImage_detail

@python_2_unicode_compatible  # only if you need to support Python 2
class SetMenu(models.Model):
    chinesetable  = models.ForeignKey(ChineseTable, on_delete=models.CASCADE)
    setMenu_number = models.CharField(max_length=5)
    setMenu_price = models.IntegerField(default=1)
    setMenu_name = models.CharField(max_length=100)
    setMenu_detail = models.TextField()
    def __str__(self):
        return self.setMenu_name
    

myapp/caterlist/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.db.models import Q
from .models import ChineseTable, FoodImage, SetMenu

class IndexView(generic.ListView):
    model = ChineseTable
    template_name = 'caterlist/index.html'
# Create your views here.

class CateringList(generic.ListView):
	model = ChineseTable
	template_name = 'caterlist/chinesetable_list.html'

class ChineseDetailView(generic.DetailView):
    model = ChineseTable
    template_name = 'caterlist/chinesetable_detail.html'
    # def get_context_data(self, **kwargs):
    #     context = super(ChineseDetailView, self).get_context_data(**kwargs)
    #     context['now'] = timezone.now()
    #     return context

def search(request):
	if 'placeText' in request.GET and request.GET['placeText']:
		q = request.GET['placeText']
		order_some = 'price_start_asc'
		url_order_by_prst_asc = '/search/?placeText=' + request.GET['placeText'] + '&price_start=' + request.GET['price_start'] + '&price_end=' + request.GET['price_end'] + '&order_by=price_start_asc'
		url_order_by_prst_desc= '/search/?placeText=' + request.GET['placeText'] + '&price_start=' + request.GET['price_start'] + '&price_end=' + request.GET['price_end'] + '&order_by=price_start_desc'
		url_order_by_pren_asc= '/search/?placeText=' + request.GET['placeText'] + '&price_start=' + request.GET['price_start'] + '&price_end=' + request.GET['price_end'] + '&order_by=price_end_asc'
		url_order_by_pren_desc= '/search/?placeText=' + request.GET['placeText'] + '&price_start=' + request.GET['price_start'] + '&price_end=' + request.GET['price_end'] + '&order_by=price_end_desc'
		if request.GET['price_start']:
			price_start = request.GET['price_start']
		else:
			price_start = 0
		if request.GET['price_end']:
			price_end = request.GET['price_end']
		else:
			price_end = 10000
		if 'order_by' in request.GET and request.GET['order_by']:
			order_some = request.GET['order_by']
			print(order_some)
		# else if request.GET['order_by_prst_desc']:
		# 	order_some = request.GET['order_by_prst_desc']

        places = ChineseTable.objects.filter(Q(place_for_service_text__icontains=q,price_start_number__lte= price_start) | Q(price_start_number__lte = price_end),Q(price_end_number__gte= price_start) | Q(price_end_number__gte = price_end)).order_by('price_start_number')
        setMenu = SetMenu.objects.all()
        return render(request, 'caterlist/chinesetable_searchresult.html',
            {'places': places, 'order': order_some, 'url_order_by_prst_asc':url_order_by_prst_asc, 'url_order_by_prst_desc': url_order_by_prst_desc, 'url_order_by_pren_asc':url_order_by_pren_asc, 'url_order_by_pren_desc':url_order_by_pren_desc, 'setmenu': setMenu,'query': q, 'price_start': price_start, 'price_end': price_end})

myapp/caterlist/templates/caterlist/chinesetable_detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Test</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> 
	<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/bootstrap-slider.min.js"></script>
	<script src="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
	<link rel="stylesheet" type="text/css" href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/css/bootstrap-slider.min.css">
	{# Load the tag library #}
	{% load bootstrap3 %}

	{# Load CSS and JavaScript #}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	<style type="text/css">
	.black-background{
		background-color: #E04410;
	}
	.black-text{
		font-size: 18px !important;
	}
	</style>
</head>
<body>
	<nav class="navbar navbar-default black-background">
	  <div class="container container-fluid">
	    <div class="navbar-header">
	       <a href="/"><h1>CatCen</h1></a> 
	    </div>
	    <ul class="nav navbar-nav navbar-right">
	    	<li class="active">
    			<a class="black-text" href="/chinesetable_list">List Restautants</a>
    		</li>
    		<li class="active">
    			<a class="black-text" href="#">Contact Us</a>
    		</li>
    	  </ul>
	  </div>
	</nav>
	  	<div class="container">
	  	   <h1>{{ object.title_text }}</a></h1> 
  		   <div class="row">
				<div class="col-md-6">										
					<img src="{% static object.filename %}" class="img-thumbnail">
				</div>
				<div class="col-md-6">
					<h2>รายละเอียด</h2>
					<p></p><label>{{ object.description_text}}</label>
					<label>สถานที่ให้บริการ  : {{ object.place_for_service_text}}</label>
					<p></p><label>ตั้งอยู่ที่  : {{ object.location_text}}</label>
					<p></p><label>ช่วงราคา : {{ object.price_start_number}} - {{object.price_end_number}}</label>
				</div>
			</div>
			<p></p>
			<p></p>
			<h1>รายการชุดอาหาร</h1>
			{% for menu in chinesetable.setmenu_set.all %}
			<div class="row">
				<h3> {{ menu.setMenu_number }} {{ menu.setMenu_name }} ราคา {{ menu.setMenu_price }} บาท</h3> 
				<p>
				<h3> เมนูอาหาร : {{ menu.setMenu_detail }} </h3>
			</div>
			{% endfor %}
			
	  	</div>
</body>

myapp/caterlist/templates/caterlist/chinesetable_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Test</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> 
	<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/bootstrap-slider.min.js"></script>
	<script src="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
	<link rel="stylesheet" type="text/css" href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/css/bootstrap-slider.min.css">
	{# Load the tag library #}
	{% load bootstrap3 %}

	{# Load CSS and JavaScript #}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	<style type="text/css">
	.black-background{
		background-color: #E04410;
	}
	.black-text{
		font-size: 18px !important;
	}
	</style>
</head>
<body>
	<nav class="navbar navbar-default black-background">
	  <div class="container container-fluid">
	    <div class="navbar-header">		        
	    	<a href="/"><h1>CatCen</h1></a>     
	    </div>
	    <ul class="nav navbar-nav navbar-right">
	    	<li class="active">
    			<a class="black-text" href="/chinesetable_list">List Restautants</a>
    		</li>
    		<li class="active">
    			<a class="black-text" href="#">Contact Us</a>
    		</li>
    	  </ul>
	  </div>
	</nav>
	  	<div class="container">
	  		{% for place in object_list %}
	    	<div class="row">
		    	<div class="col-md-2">
					
		    	</div>
		    	<div class="col-md-4">
		    		<img src="{% static place.filename %}" class="img-thumbnail sizing" alt="140x140">
		    	</div>
		    	<div class="col-md-4">
		    		<p>
		    		<label>{{place.title_text}}</label>
		    		<label>{{place.setmenu.setMenu_number}}</label>
		    		<p><label>ช่วงราคา : {{place.price_start_number}} - {{place.price_end_number}} บาท</label>
		    		<p><label>สถานที่ที่ให้บริการ : {{place.place_for_service_text}}</label>
		    		<p><label>สถานที่ตั้ง : {{place.location_text}}</label>
		    		{% for menu in place.setmenu_set.all|slice:":1" %}
			    			{% if menu.chinesetable_id == place.id %}
					    	<div>
					    		<p><label>ชุดอาหารเริ่มต้น : </label>
								<label> {{ menu.setMenu_number }} {{ menu.setMenu_name }} ราคา {{ menu.setMenu_price }} บาท</label> 
								<p>
								<label> เมนูอาหาร : {{ menu.setMenu_detail }} </label>
							</div>
							{% endif %}
					{% endfor %}				
	    	</div>
	    </div>
	    <p>
	    {% endfor %}
			
	  	</div>
</body>

myapp/caterlist/templates/caterlist/chinesetable_searchresult.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Test</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> 
	<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/bootstrap-slider.min.js"></script>
	<script src="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
	<link rel="stylesheet" type="text/css" href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/css/bootstrap-slider.min.css">
	{# Load the tag library #}
	{% load bootstrap3 %}

	{# Load CSS and JavaScript #}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	<style type="text/css">
	.black-background{
		background-color: #E04410;
	}
	.black-text{
		font-size: 18px !important;
	}
	.pad-top{
		padding-top: 10%;
	}
	.pad-bottom{
		padding-bottom: 10%;
		z-index: 10;
		position: relative;
	}
	.layer-index{
		position: fixed;
		z-index: 1;
	}
	.background{
		background-color: #FFFFFF !important;
		opacity: 0.95;
	}
	#image-head{
		position: absolute;
		width: 100%;
		height: 800px;
	}
	.sizing{
		width: 340px;
		height: 200px;
	}
	.bg-color-long{
		background-color: #DEDEDE;
		border-radius: 25px;
		position: absolute;
	}
	@media (max-width: 992px) {
		.bg-color-long{
		background-color: #DEDEDE;
		border-radius: 25px;
		position: relative;
		}
	}
	</style>
</head>
<body>
	<nav class="navbar navbar-default black-background">
	  <div class="container container-fluid">
	    <div class="navbar-header">
	        <a href="/"><h1>CatCen</h1></a>
	    </div>
	    <ul class="nav navbar-nav navbar-right">
	    	<li class="active">
    			<a class="black-text" href="/chinesetable_list">List Restautants</a>
    		</li>
    		<li class="active">
    			<a class="black-text" href="#">Contact Us</a>
    		</li>
    	  </ul>
	  </div>
	</nav>
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<p>You searched for: <strong>{{ query }}</strong></p>
				Price {{price_start}} - {{price_end}}
			{% if places %}
		    	<p>Found {{ places|length }} book{{ places|pluralize }}.</p>
		    </div>
		    <div class="col-md-3">
		    	
		    </div>
		    <div class="col-md-3">
			    <div class="btn-group" role="group">
			    	<div class="dropdown">
			    			<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
	    					ราคาเริ่มต้น
	    					 <span class="caret"></span>
	    					</button>
	    				<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			    			<li><a href="{{ url_order_by_pren_asc }}" title="">จากราคาต่ำไปสูง</a></li>
			   	 			<li><a href="{{ url_order_by_pren_desc }}" title="">จากราคาสูงไปต่ำ</a></li>
			   	 		</ul>
			   	 	</div>
			   	 </div>
			   	<div class="btn-group" role="group">
			   	 	<div class="dropdown">
			    			<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
	    					ราคาสิ้นสุด
	    					 <span class="caret"></span>
	    					</button>
	    				<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			    			<li><a href="{{ url_order_by_prst_asc }}" title="">จากราคาต่ำไปสูง</a></li>
			   	 			<li><a href="{{ url_order_by_prst_desc }}" title="">จากราคาสูงไปต่ำ</a></li>
			   	 		</ul>
			   	 	</div>
			   	</div>
		    </div>
	    </div>
    		<div class="col-md-3 bg-color-long">
			  <form id="form-search" method="GET" action="/search" class="submit-form" role="search">
		    	{% csrf_token %}
		        <div class="col-md-12">
		        	<p></p>
		        	<label>จังหวัดที่ต้องการจัดงาน</label>
		          	<input id="province" type="text" name="placeText" class="form-control" placeholder="Search">
		        </div>
		        <div class="col-md-12">
		        	<label>ต้องการจองวันที่</label>
			        <div class="input-group date" id="datetimepicker" data-provide="datepicker">
					    <input type="text" class="form-control">
					    <div class="input-group-addon">
					        <span class="glyphicon glyphicon-th"></span>
					    </div>
					</div>
				</div>
		        <div class="col-md-12 form-group">
		        	<label>ราคาตั้งแต่ (ต่อ1โต๊ะ)</label>
		          	<input type="number" name="price_start" class="form-control" placeholder="">
		        </div>
		        <div class="col-md-12 form-group">
		        	<label>จนถึง</label>
		          	<input type="number" name="price_end"  class="form-control" placeholder="">
		        </div>
		        <div class="col-md-12 form-group">
		        	<input id="submit-request" type="submit" class="btn btn-success btn-block" value="Submit">
		        </div>
      		</form>			
    	</div>
    	{% if order == 'price_start_asc' %}
    		{% for place in places|dictsort:"price_start_number" %}
		    <div class="row">
		    	<div class="col-md-4">
					
		    	</div>
		    	<div class="col-md-4">
		    		<img src="{% static place.filename %}" class="img-thumbnail sizing" alt="140x140">
		    	</div>
		    	<div class="col-md-4">
		    		<p>
		    		<label>{{place.title_text}}</label>
		    		<label>{{place.setmenu.setMenu_number}}</label>
		    		<p><label>ช่วงราคา : {{place.price_start_number}} - {{place.price_end_number}}</label>
		    		<p><label>สถานที่ที่ให้บริการ : {{place.place_for_service_text}}</label>
		    		<p><label>สถานที่ตั้ง : {{place.location_text}}</label>
		    		{% for menu in setmenu|slice:":1" %}
			    			{% if menu.chinesetable_id == place.id %}
					    	<div>
					    		<p><label>ชุดอาหารเริ่มต้น : </label>
								<label> {{ menu.setMenu_number }} {{ menu.setMenu_name }} ราคา {{ menu.setMenu_price }} บาท</label> 
								<p>
								<label> เมนูอาหาร : {{ menu.setMenu_detail }} </label>
							</div>
							{% endif %}
					{% endfor %}				
		    	</div>
		    </div>
		    <p>
	    	{% endfor %}
	    {% endif %}
    	{% if order == 'price_start_desc' %}
    		{% for place in places|dictsortreversed:"price_start_number" %}
		    <div class="row">
		    	<div class="col-md-4">
					
		    	</div>
		    	<div class="col-md-4">
		    		<img src="{% static place.filename %}" class="img-thumbnail sizing" alt="140x140">
		    	</div>
		    	<div class="col-md-4">
		    		<p>
		    		<label>{{place.title_text}}</label>
		    		<label>{{place.setmenu.setMenu_number}}</label>
		    		<p><label>ช่วงราคา : {{place.price_start_number}} - {{place.price_end_number}}</label>
		    		<p><label>สถานที่ที่ให้บริการ : {{place.place_for_service_text}}</label>
		    		<p><label>สถานที่ตั้ง : {{place.location_text}}</label>
		    		{% for menu in setmenu|slice:":1" %}
			    			{% if menu.chinesetable_id == place.id %}
					    	<div>
					    		<p><label>ชุดอาหารเริ่มต้น : </label>
								<label> {{ menu.setMenu_number }} {{ menu.setMenu_name }} ราคา {{ menu.setMenu_price }} บาท</label> 
								<p>
								<label> เมนูอาหาร : {{ menu.setMenu_detail }} </label>
							</div>
							{% endif %}
					{% endfor %}				
		    	</div>
		    </div>
		    <p>
	    	{% endfor %}
	    	{% endif %}
	    	{% if order == 'price_end_asc' %}
    		{% for place in places|dictsort:"price_end_number" %}
		    <div class="row">
		    	<div class="col-md-4">
					
		    	</div>
		    	<div class="col-md-4">
		    		<img src="{% static place.filename %}" class="img-thumbnail sizing" alt="140x140">
		    	</div>
		    	<div class="col-md-4">
		    		<p>
		    		<label>{{place.title_text}}</label>
		    		<label>{{place.setmenu.setMenu_number}}</label>
		    		<p><label>ช่วงราคา : {{place.price_start_number}} - {{place.price_end_number}}</label>
		    		<p><label>สถานที่ที่ให้บริการ : {{place.place_for_service_text}}</label>
		    		<p><label>สถานที่ตั้ง : {{place.location_text}}</label>
		    		{% for menu in setmenu|slice:":1" %}
			    			{% if menu.chinesetable_id == place.id %}
					    	<div>
					    		<p><label>ชุดอาหารเริ่มต้น : </label>
								<label> {{ menu.setMenu_number }} {{ menu.setMenu_name }} ราคา {{ menu.setMenu_price }} บาท</label> 
								<p>
								<label> เมนูอาหาร : {{ menu.setMenu_detail }} </label>
							</div>
							{% endif %}
					{% endfor %}				
		    	</div>
		    </div>
		    <p>
	    	{% endfor %}
	    	{% endif %}
	    	{% if order == 'price_end_desc' %}
    		{% for place in places|dictsort:"price_end_number" %}
		    <div class="row">
		    	<div class="col-md-4">
					
		    	</div>
		    	<div class="col-md-4">
		    		<img src="{% static place.filename %}" class="img-thumbnail sizing" alt="140x140">
		    	</div>
		    	<div class="col-md-4">
		    		<p>
		    		<label>{{place.title_text}}</label>
		    		<label>{{place.setmenu.setMenu_number}}</label>
		    		<p><label>ช่วงราคา : {{place.price_start_number}} - {{place.price_end_number}}</label>
		    		<p><label>สถานที่ที่ให้บริการ : {{place.place_for_service_text}}</label>
		    		<p><label>สถานที่ตั้ง : {{place.location_text}}</label>
		    		{% for menu in setmenu|slice:":1" %}
			    			{% if menu.chinesetable_id == place.id %}
					    	<div>
					    		<p><label>ชุดอาหารเริ่มต้น : </label>
								<label> {{ menu.setMenu_number }} {{ menu.setMenu_name }} ราคา {{ menu.setMenu_price }} บาท</label> 
								<p>
								<label> เมนูอาหาร : {{ menu.setMenu_detail }} </label>
							</div>
							{% endif %}
					{% endfor %}				
		    	</div>
		    </div>
		    <p>
	    	{% endfor %}
	    	{% endif %}
	{% else %}
	    <p>No books matched your search criteria.</p>
	{% endif %}
	</div>
	
</body>

myapp/caterlist/templates/caterlist/index.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Test</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> 
	<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/bootstrap-slider.min.js"></script>
	<script src="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
	<link rel="stylesheet" type="text/css" href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/6.0.16/css/bootstrap-slider.min.css">
	{# Load the tag library #}
	{% load bootstrap3 %}

	{# Load CSS and JavaScript #}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	<style type="text/css">
	.black-background{
		background-color: #E04410;
	}
	.black-text{
		font-size: 18px !important;
	}
	.spacing{
		padding-top: 10%;
		padding-bottom: 10%;
	}
	.bottom{
		margin-bottom: 20%;
		z-index: 10;
		position: relative;
	}
	.layer-index{
		position: fixed;
		z-index: 1;
	}
	.background{
		background-color: #FFFFFF !important;
		border-radius: 15px;
		opacity: 0.95;
	}
	.menu-top{
		font-size: 20px;
	}
	.menu-align{
		vertical-align: middle;
	}
	.height-footer{
		height: 100px;
	}
	#image-head{
		position: absolute;
		width: 100%;
		height: 450px;
	}
	#image-logo{
		width: auto;
		height: 100px;
	}
	footer{
		padding-top: 60px;
	}
	</style>
	<script type="text/javascript">
		$(document).ready(function() {
			// body...
            $('#datetimepicker').datetimepicker();
            $('#form-search').submit(function(event){
            	if($('#province').val() != "")
            	{
            		console.log('Not good');
            	}else{
            		event.preventDefault();
            	}
            });
		});
		
	</script>
</head>
<body>
	<div class="container">
		<nav class="navbar">
			<div class="container-fluid">
			    <div class="navbar-header menu-align">
			    	<a class="nav-brand">
			        	<img id="image-logo" src="{% static 'logo-cattcen.png' %}"  alt="Responsive image">   
			        </a>
			    </div>
			    <ul class="nav navbar-nav nav-pills navbar-right">
				  <li role="presentation"><a class="menu-top" href="/chinesetable_list">List Restaurants</a></li>
				  <li role="presentation"><a class="menu-top" href="#">Make Request</a></li>
				  <li role="presentation"><a class="menu-top" href="#">Contact Us</a></li>
				</ul>
			</div>
		</nav>
	</div>
	<img id="image-head" src="{% static 'hot-buffet.jpg' %}" class="img-responsive" alt="Responsive image">
	<div class="container spacing">
		
		  <div class="row background bottom">
			    <form id="form-search" method="GET" action="search/" class="submit-form" role="search">
			    {% csrf_token %}
			        <div class="col-md-4 form-group ">
			        	<p></p>
			        	<label>จังหวัดที่ต้องการจัดงาน</label>
			          	<input id="province" type="text" name="placeText" class="form-control" placeholder="Search">
			        </div>
			        <div class="col-md-3 form-group">
			        	<p></p>
			        	<label>จำนวนผู้ร่วมงาน</label>
				        <input type="number" name="price_start" class="form-control" placeholder="">
					</div>
			        <div class="col-md-2 form-group">
			        	<p></p>
			        	<label>ราคาตั้งแต่ (ต่อ1โต๊ะ)</label>
			          	<input type="number" name="price_start" class="form-control" placeholder="">
			        </div>
			        <div class="col-md-2 form-group">
			        	<p></p>
			        	<label>จนถึง</label>
			          	<input type="number" name="price_end"  class="form-control" placeholder="">
			        </div>
			        <div class="col-md-1 form-group">
			        	<p></p>
			        	<label>ยืนยัน</label>
			        	<input id="submit-request" type="submit" class="btn btn-success" value="Submit">
			        </div>
	      		</form>
	  	</div>
	  	{% if object_list %}
	  	<div>
	  		<div style="background-color:white; opacity:0.98">
	  		   <div class="row">
			{% for table in object_list %}	
				<div class="col-md-4">
					<h1><a href="{% url 'caterlist:chinesetable' table.id %}">{{ table.title_text }}</a></h1> 					
					<img src="{% static table.filename %}" class="img-thumbnail">
					<p></p><label>{{ table.description_text}}</label>
					<label>สถานที่ให้บริการ  : {{ table.place_for_service_text}}</label>
					<p></p><label>ตั้งอยู่ที่  : {{ table.location_text}}</label>
				</div>
			{% endfor %}
			</div>
	  		</div>
	  	</div>
		{% endif %}
	</div>
	<div class="navbar-default height-footer">
		<div class="container">
			<h5>Copyright Reserved Cattcen.com</h5>
		</div>
	</div>
</body>
</html>